name: Release

on:
  release:
    types: created

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  release-build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set version
      run: |
        sed -i "" "s/\(static let version = \"\).*\(\"\)/\1${TAG}\2/" Sources/rswift/Rswift.swift
      env:
        TAG: ${{ github.event.release.tag_name }}

    - name: Build
      run: swift build -v -c release
    - name: Code Sign
      run: |
        codesign --force --options runtime --sign 'Developer ID Application: Mathijs Kadijk (5Z49PA849J)' .build/release/rswift
    - name: Archive
      run: zip --junk-paths ${{ runner.temp }}/archive.zip .build/release/rswift License
    - name: Package
      run: |
        pkgbuild --root .build/release --identifier "nl.mathijskadijk.rswift" --version $TAG_NAME --install-location "/Applications" --sign "Developer ID Installer: Mathijs Kadijk (5Z49PA849J)" $FILENAME
      env:
        TAG_NAME: ${{ github.event.release.tag_name }}
        FILENAME: rswift-${{ github.event.release.tag_name }}.pkg
        BUNDLE_ID: nl.mathijskadijk.rswift
    - name: Notarize
      run: |
        sh notarize.sh
      env:
        BUNDLE_ID: nl.mathijskadijk.rswift
        DEV_ACCOUNT: mkadijk@gmail.com
        PASSWORD: ${{ secrets.PASSWORD }}
        DEV_TEAM: 5Z49PA849J
        FILENAME: rswift-${{ github.event.release.tag_name }}.pkg
    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ runner.temp }}/archive.zip
        asset_name: rswift-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip

    - name: Store artifact
      uses: actions/upload-artifact@v1
      with:
        name: rswift-${{ github.event.release.tag_name }}
        path: .build/release/rswift

    - name: Publish to Cocoapods
      run: |
        export POD_VERSION=$(echo $TAG_NAME | cut -c2-)
        pod trunk push
      env:
        TAG_NAME: ${{ github.event.release.tag_name }}
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
